### ISSUE TITLE
Role stopped working with ansible 2.14.x

### ISSUE THREAD

**Issue by Danoontjes** [alexeychusta/ansible-firewall#1]
The role no longer works with ansible version 2.14.x because is uses the 'warn' argument to silence some messages. That has been deprecated in this ansible version.
The error looks like this:
```
TASK [ansible-firewall : Check if firewalld package is installed (on RHEL).] ******************************************************************************************************************************************************************************************************************
fatal: [10.5.87.34]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: strip_empty_ends, argv, _raw_params, creates, removes, executable, chdir, _uses_shell, stdin, stdin_add_newline."}
...ignoring

TASK [ansible-firewall : Disable the firewalld service (on RHEL, if configured).] *************************************************************************************************************************************************************************************************************
fatal: [10.5.87.34]: FAILED! => {"msg": "The conditional check 'firewalld_installed.rc == 0' failed. The error was: error while evaluating conditional (firewalld_installed.rc == 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/root/.ansible/roles/ansible-firewall/tasks/disable-other-firewalls.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Disable the firewalld service (on RHEL, if configured).\n  ^ here\n"}
```
You can fix it by removing the following lines from https://github.com/alexeychusta/ansible-firewall/blob/main/tasks/disable-other-firewalls.yml (lines 3-4, 26-27 and 48-49)
```
  args:
    warn: false
```
It should work again after that.
